Repository Aman-Mandal/groovy, pull requests merged in 2022-10, with the labels that each got.

#37 Work on player (play/pause functionality)
  .vscode/settings.json
  components/Navbar/Navbar.jsx
  components/Player/Player.jsx
  components/Player/Player.tsx
  components/Sidebar/Sidebar.jsx
  components/Trending/Trending.jsx
  contexts/ContextProvider.js
  pages/Explore.jsx
  public/sample_music.mp3
  styles/globals.css
  tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#38 fixed the genres section and reduced the image size of artist section
  components/Artist/Artist.jsx
  components/Genres/Genres.jsx
  components/TopArtists/TopArtists.jsx
  data/data.js
Labels: hacktoberfest, hacktoberfest-accepted

#41 Top charts component added
  components/TopCharts/TopCharts.jsx
  pages/Explore.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#40 Solution for issue regarding making trending new hits scrollable and dynamic (issue #26)
  components/Trending/Trending.jsx
  data/trendingSongsData.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#59 Navbar bugs, minor UI fixes and removal of unused code.
  components/Artist/Artist.jsx
  components/Header/Header.jsx
  components/Navbar/Navbar.jsx
  components/Navbar/SearchBar.jsx
  components/Sidebar/Sidebar.jsx
  components/TopArtists/TopArtists.jsx
  components/Trending/Trending.jsx
  components/index.jsx
  index.js
  pages/Albums.jsx
  pages/Artists.jsx
  pages/Explore.jsx
  pages/Favourites.jsx
  pages/Genres.jsx
  pages/Local.jsx
  pages/Radio.jsx
  pages/Recent.jsx
  pages/_app.js
Labels: hacktoberfest, hacktoberfest-accepted

#77 refactor: chage cursor to pointer on hovering sidebar title
  components/Sidebar/Sidebar.jsx
Labels: hacktoberfest-accepted

#79 Shazam top tracks
  .env
  components/TopCharts/TopCharts.jsx
  next.config.js
  package-lock.json
  package.json
  pages/Explore.jsx
  pages/api/top/charts.js
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#83 fix(sidebar): remove duplicate Albums label in sidebar
  data/data.js
Labels: hacktoberfest, hacktoberfest-accepted

#87 Added the design figma file
  design/Mobile- Explore_page/Explore-Page
  design/alubms page/Groovy-Albums_page_updated.fig
  design/alubms page/Groovy_Album_page.txt
Labels: hacktoberfest, hacktoberfest-accepted

#98 Issue #97 fixed. More detail in the PR comments
  components/TopCharts/TopCharts.jsx
  yarn.lock
Labels: bug, hacktoberfest, hacktoberfest-accepted

#100 Added a floating playing controls - that controls the now playing song and sits at the bottom of the site
  components/Footer/FloatingPlayer.jsx
  components/Footer/Volume.jsx
  components/Player/NowPlayingImage.jsx
  components/Player/Player.jsx
  components/Player/PlayerControls.jsx
  contexts/ContextProvider.js
  pages/_app.js
Labels: hacktoberfest, hacktoberfest-accepted

#103 made top artists dynamic,
  components/Artist/Artist.jsx
  components/TopArtists/TopArtists.jsx
  components/TopCharts/TopCharts.jsx
  contexts/ContextProvider.js
  pages/Explore.jsx
Labels: enhancement

#118 Added Contributors to the Readme section
  README.md
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#149 Mobile explore responsive
  components/Footer/FloatingPlayer.jsx
  components/Navbar/Navbar.jsx
  components/Player/NowPlayingImage.jsx
  components/Player/Player.jsx
  components/Player/PlayerControls.jsx
  components/Sidebar/Sidebar.jsx
  pages/_app.js
Labels: hacktoberfest-accepted
